### PR TITLE
Update README build section

### PR DESCRIPTION
**Pull request by NiccoloGranieri**
Update README build section providing more information to the user on how to setup autokbisw as a background progress that launches at login when building from source.

### CODE REVIEW

**Comment by NiccoloGranieri** [comment]
Thanks for spotting that! If I think you could make changes to the PR before merging, so feel free to add the ~.

I will be happy to answer questions on that topic, even though I'm not sure how many questions there will be about it! :)

**Comment by NiccoloGranieri** [comment]
Fixed @ohueter !

**Comment by ohueter** [comment]
Thanks a lot for your effort Niccolo! 

To be completely honest, I now have thought about this for a while and tend to not accept this PR. 

There used to be a section like this in the README, you can review the deleted part in the commit diff: https://github.com/ohueter/autokbisw/commit/20da3d1370d794af9ad2c01bba3579babc0c7e2f#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L53-L95

As you can see, there were already some sections on how to handle common pitfalls. Moreover, the `load` und `unload` launchctl commands are considered legacy. The new `bootstrap` command is more difficult to use.

To me, all of this this seems pretty complicated stuff thats mostly out of scope for this repository, and I'm unwilling to handle possible support requests (and I'm sure you're not too keen either, thanks for offering your help though!). autokbisw is supposed to be installed via Homebrew, and if users decide to take another path, they have to figure out the consequences on their own.

However, the deleted content and your additions might be a better fit for a technical blog post somewhere on how to launch background tasks in macOS.

I hope you can understand my reasoning.
Best wishes, Ole

**Comment by NiccoloGranieri** [comment]
I completely get your POV @ohueter, thanks for taking the time to review the PR anyways.

**Pull request closed without merging**
