### PR TITLE
Add action to provide binary

### PR DESCRIPTION
**Pull request by ces92**
This action provides a binary for each release with the format autokbisw-{{tag}}.

### CODE REVIEW

**Comment by ohueter** [comment]
Thanks a lot for your contribution @ces92, great idea & looking good!

Personally I would prefer to release a zip archive of the binary (`autokbisw-{{tag}}.zip` or so). There seem to be a few Actions for that, and probably the `zip` command is available on the runner machines as well. Would you be willing to look into this?

**Comment by ces92** [comment]
@ohueter Yes, I will have a look in the next days.

**Comment by ces92** [comment]
@ohueter Now the binary will be uploaded as zip file with every release.

**Comment by ohueter** [comment]
Looks good to me, let's merge this. Thanks again @ces92!

**Pull request merged**
