### PR TITLE
Fix for some keyboards not working properly and minor code improvements

### PR DESCRIPTION
**Pull request by legobrick**
# Reasons for this PR

- There was a bug preventing events from particular keyboards from being stored. In the screenshot, an example of what was happening with my Keychron Q3.

- Comments within the code and logs
- Added a lock to prevent race condition when typing with a different keyboard and changing language in the meantime (despite this might only verifyby running this program twice)
- Storing a Codable instead of a bare string, to support extensibility

### CODE REVIEW

**Comment by ohueter** [comment]
Hi @legobrick, thanks a lot for your PR. I'm on vacation during the Easter holidays and will take a closer look afterwards!

**Comment by ohueter** [comment]
Hi @legobrick, thanks for your patience. :-)

This seems like a great refactoring, the code is much better structured and more readable. Nice 👍 

I do fear, however, that the `conformsToKeyboard` change will make the software fail again for some Logitech mice that identify as keyboard for whatever reason (see @ryanmccardle's PR #3).

It seems like there is no "automagic" solution for this problem. Maybe we could:
1. Add a hardcoded list of device IDs to the code that are known to behave irregularly and are forced to either be treated as keyboard, or be ignored; or
2. make the list of known devices (mice and keyboards) somehow editable and let the user set a flag for each device if it should trigger the input schema switch. A default value for this flag could be determined on the currently implemented logic. Then the majority of users would never need to edit this list.

Can you think of another way to handle this? I'm very open to discussion :-) 

Personally, option 2 seems to be the way to go. Can the device list somehow be persisted to the filesystem in the user home folder?

**Comment by ohueter** [comment]
Ok I did some digging and here's what I found out and my proposal on how to proceed:

The keyboard <-> layout mapping is stored in [UserDefaults](https://developer.apple.com/documentation/foundation/userdefaults). It can be read in the terminal via `defaults read autokbisw`. Here's an example output from my system:

```
$ defaults read autokbisw
{
    keyboardISMapping =     {
        "" = "com.apple.keylayout.US";
        "Apple Internal Keyboard / Trackpad-[1452-833-Apple Inc.-FM7130406TNN4L2B5+TCT]" = "com.apple.keylayout.US";
        "Apple Keyboard-[1452-545-Apple, Inc-unknown]" = "com.apple.keylayout.German";
        "Apple Keyboard-[1452-591-Apple Inc.-unknown]" = "com.apple.keylayout.US";
        "Apple Keyboard-[1452-592-Apple Inc.-unknown]" = "com.apple.keylayout.German";
        "TouchBarUserDevice-[1452-34304-unknown-unknown]" = "com.apple.keylayout.German";
    };
}
```

We could change the format of the `value` to a dictionary containing a boolean flag `active` and the `layout` as a string, as before, e.g.

```
{
    "Apple Keyboard-[1452-592-Apple Inc.-unknown]" = {
        active = true;
        layout = "com.apple.keylayout.US";
    };
}
```

Every device that identifies as a mouse or keyboard is added to this mapping, with the value of `conformsToKeyboard` as default for the `active` flag. `autokbisw` would only switch the keyboard layout if `active == true`.

Because writing keys in nested dictionaries seems to be impossible with `defaults`, we would need to extend `autokbisw`'s CLI to do that, e.g.

```
$ autokbisw list
1. "Apple Keyboard-[1452-545-Apple, Inc-unknown]" = { active = true; layout = "com.apple.keylayout.German"};
2. "Apple Keyboard-[1452-591-Apple Inc.-unknown]" = {active = true; layout = "com.apple.keylayout.US" };

$ autokbisw disable 1
Disabled automatic keyboard layout switching for device 1 (Apple Keyboard-[1452-545-Apple, Inc-unknown]).

$ autokbisw enable 1
Enabled automatic keyboard layout switching for device 1 (Apple Keyboard-[1452-545-Apple, Inc-unknown]).

$ $ autokbisw layout list
(... somehow retrieve from OS ...)
French
German
US
(...)

$ autokbisw layout 1 US
Set keyboard layout for device 1 (Apple Keyboard-[1452-545-Apple, Inc-unknown]) to com.apple.keylayout.US.
```

So, we could proceed like that:

1. I need to test this PR, happening asap.
2. Merge this PR, but don't create a release (-> not available via Homebrew, because it would potentially be a breaking change for existing users).

-- so far regarding this PR --

3. Update the data format in user defaults.
4. Add a CLI interface to list known input devices and set them active/inactive.
5. Update docs, release to Homebrew.

Would greatly appreciate your feedback. :)

**Comment by ryanmccardle** [comment]
Having it be set in the CLI seems like a good solution to me, and easier than trying to maintain a list of devices. I suppose we are dealing with 3 or 4 kinds of weird devices here:
- Mice that conform to keyboard & mouse for no good reason I can see
- Keyboards that conform to keyboard & mouse for no good reason I can see
- Presumeably keyboards with built in touch pads conform to keyboard & mouse as well? Or maybe some show up as two seperate devices?
- Keyboard and mice combos with a single dongle, maybe some show up as single device which conforms to keyboard & mouse?

Perhaps another way around it would be trying to figure out if the event is a mouse move or click and then ignoring those, but then that might get more difficult with mice with large numbers of buttons... If I have some time I'll see if that works with my logitech mouse.

Setting the language in the CLI would be nice to have I suppose, but pretty easy to do the current way.

**Comment by ohueter** [comment]
Hi Ryan, thanks for your input! I created #24 and #25 to organize work on what we discussed. I'll merge your PR into [#v1.5](https://github.com/ohueter/autokbisw/tree/v1.5). I hope this goes into a direction you can agree with. Really appreciate your contribution to this project!

**Review by ohueter — APPROVED** [review]

**Pull request merged**
